### ISSUE TITLE
Sonification To-Do

### ISSUE THREAD

**Issue by Kizjkre** [Kizjkre/ocean-memory#8]
# Sonification tasks:
- [ ] Finish sonification for tracks
  - [x] Sonify text through segmentation
- [ ] Sonify channels
  - [x] Finish backend for sonifying channels
- [ ] Implement frequency modulation
- [ ] Implement granular synthesis
- [ ] Export sounds
- [x] Provide datasets
- [ ] Coding environment for extensible development

**Comment by Kizjkre** [comment]
Outdated
