### ISSUE TITLE
Frontend To-Do

### ISSUE THREAD

**Issue by Kizjkre** [Kizjkre/ocean-memory#9]
# Frontend To-Do
- [x] Split `rootReducer` into multiple reducers ~(see `combineReducers`)~ (Requires `redux`, so implement own)
  - [x] `globalSettingsReducer`
- [x] Refactor actions (make more specific)
  - [x] `globalSettings`
- [x] Adjust where processing is happening (ex: CSV should be parsed in action rather than in `Toolbar` component) https://github.com/Kizjkre/ocean-memory/blob/32faf350a2873abfc67b7eaccb711ddb089f45b7/frontend/src/components/workstation/Toolbar.js#L12
- [ ] Somehow display non-numerical data on tracks.
- [x] Export current state with `.json`.
- [x] Import state.

**Comment by Kizjkre** [comment]
Outdated
